package.json, src/main.js, src/store/modules/recipient/actions.js, src/store/modules/recipient/getters.js, src/store/modules/recipient/index.js, src/store/modules/recipient/mutations.js, src/store/modules/user/actions.js, src/views/monitoringRdt/list.vue
membuat statistik atau summary recipient rdt
=> Statistik recipient RDT

src/components/Rdt/DetailRdtFaskes.vue, src/components/Rdt/MonitoringRdtKota.vue, src/lang/en.js, src/lang/id.js, src/views/monitoringRdt/detail.vue
Pembuatan Layout Detail RDT setiap Faskes/Institusi.
Sudah berdasarkan login dan sudah menyambung dengan monitoring.
data yang digunakan masih data dummy dan hanya berupa layout.
=> Layout tampilan Detail Penggunaan RDT tingkat Faskes

src/components/DatePicker/index.vue, src/components/SelectRegion/DistrictCity/index.vue, src/components/SelectRegion/SubDistrict/index.vue, src/lang/id.js, src/utils/vee-validate.js, src/views/distribusiRdt/form.vue
Trello:
https://trello.com/c/bq5CjfDx/15-distribusi-tambah-distribusi-rdt-di-tingkat-provinsi
=> perubahan validasi dan meperbaiki form input

src/components/DatePicker/index.vue, src/lang/id.js, src/views/distribusiRdt/list.vue
Perbaikan kotak datepicker, ubah desain list distribusi, menambah tulisan "tidak ada" saat data kosong, dan merefresh kembali data summary saat create dan update data distribusi
=> Perbaikan issue distribusi RDT

src/components/Rdt/DetailRdtKota.vue, src/store/modules/recipient/actions.js, src/store/modules/recipient/getters.js, src/store/modules/recipient/index.js, src/store/modules/recipient/mutations.js
Integrasi API pada Menu Detail Penggunaan RDT Kit setiap kab/kota.
=> Intergrasi API Detail Penggunaan RDT Kit

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/FirstStep.vue, src/components/ApplicationForm/ThirdStep.vue
perbaikan inputan, priview pdf file, dan hapus variable tidak digunakan
=> Form permohonan logistik perbaikan inputan

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/SecondStep.vue, src/lang/id.js
penambahan alert pada step 2, tidak dapat upload file PDF pada step 2
=> Revisi Form permohonan logistik

src/components/ApplicationForm/FirstStep.vue, src/components/ApplicationForm/ThirdStep.vue, src/lang/id.js, src/utils/vee-validate.js
Validasi jumlah pada step 3, tidak boleh kurang dari 0
https://trello.com/c/3WhXRQdE/44-permohonan-form-kebutuhan-logistik
=> Validasi tidak boleh kurang dari 0

src/components/DatePicker/index.vue, src/lang/id.js, src/router/index.js, src/router/modules/pengajuanLogistik.js, src/store/modules/logistics/actions.js, src/store/modules/logistics/getters.js, src/store/modules/logistics/index.js, src/store/modules/logistics/mutations.js, src/views/pengajuanLogistik/list.vue
Pembuatan menu list pengajuan logistik
https://trello.com/c/kmhCY2GP/41-permohonan-list-pengajuan-logistik
=> List pengajuan logistik

src/components/Rdt/MonitoringRdtKota.vue, src/components/Rdt/MonitoringRdtProvinsi.vue
1.  fix layout summary rdt province
2.  fix layout summary rdt city
=> Fix layout summary rdt

src/components/ApplicationForm/ConfirmationStep.vue
=> test delete custom css .col

src/lang/id.js, src/router/index.js, src/router/modules/masterData.js, src/store/index.js, src/store/modules/masterData/actions.js, src/store/modules/masterData/getters.js, src/store/modules/masterData/index.js, src/store/modules/masterData/mutations.js, src/views/masterData/listFasilitasKesehatan.vue
Pembuatan Menu Fasillitas Kesehatan
https://trello.com/c/nCnZAjr7/55-permohonan-list-tambahan-faskes
=> Pembuatan Menu Fasillitas Kesehatan

src/views/pengajuanLogistik/list.vue
Perbaikan filter date pada menu Alat Kesehatan
=> Perbaikan filter date

src/views/landingPage/index.vue, src/views/permohonan/formPemohon.vue
Landing page Perbubahan icon dan perubahan penamaan. dan perbaikan icon mobile
=> Landing page Perbubahan icon dan perubahan penamaan

src/components/ApplicationForm/ConfirmationStep.vue
Perubahan text menjadi rata tengah pada loading setelah submit
=> Perubahan text menjadi rata tengah

src/components/ApplicationForm/AddInstance.vue, src/components/ApplicationForm/FirstStep.vue, src/store/modules/logistics/actions.js
Submit API tambah faskes di menu form permohonan
=> Pembuatan submit tambah faskes

src/components/ApplicationForm/FirstStep.vue
=> display none tambah faskes

src/components/ApplicationForm/ThirdStep.vue, src/store/modules/logistics/actions.js
Perbaikan bug autocomplete nama APD tidak muncul karena ter-replace di step 3
=> Perbaikan list APD step 3

src/components/ApplicationForm/ConfirmationStep.vue
perbaikan pindah page menjadi menuju landing page
=> perbaikan pindah page

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/ThirdStep.vue, src/store/modules/logistics/actions.js
Perbaikan step 3 dan pindah page, seperti di production
=> Perbaikan di Production

src/components/ApplicationForm/FirstStep.vue
hapus x autocomplete nama instansi
=> hapus x autocomplete

src/views/permohonan/formPemohon.vue
perbaikan duplikat call API pada form permohonan
=> perbaikan duplikat call API

src/views/permohonan/formPemohon.vue
Perbaikan duplikat di production yang memanggil component 2 kali
=> Perbaikan duplikat di production

src/components/ApplicationForm/AddInstance.vue, src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/FirstStep.vue, src/components/ApplicationForm/FourthStep.vue, src/components/ApplicationForm/SecondStep.vue, src/components/ApplicationForm/ThirdStep.vue, src/views/permohonan/formPemohon.vue
Perbaikan penamaan css dan penghapusan css tidak terpakai pada form permohonan
=> Perbaikan css pada form permohonan

src/main.js
test fixing bug di staging request kang arif
=> text fixing bug mobile

src/main.js
=> hapus comment

src/components/ApplicationForm/AddInstance.vue, src/lang/id.js
Perbaikan typo, perbaikan dialog message, dan perbaikan key post
=> Perbaikan add instance

src/components/ApplicationForm/AddInstance.vue, src/utils/vee-validate.js
Perbaikan list tambah fakses, fakes location boleh tidak di isi
=> Perbaikan list tambah faskes

src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/update.vue
Perbaikan pilih dropdown saat update, perbaikan salah penamaan label, dan perbaikan link ktp
=> Revisi detail permohonan

src/lang/id.js
=> Perbaikan penamaan

src/views/pengajuanLogistik/list.vue
=> Perbaikan get

src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/update.vue
Perbaikan pilihan status pada update logistik
=> Perbaikan pilihan status

src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/list.vue, src/views/pengajuanLogistik/update.vue
=> Ship v1.0.6

src/router/index.js
hide menu monitoring dan distribusi RDT di production
=> Hide menu monitoring

src/components/ApplicationForm/FirstStep.vue, src/lang/id.js, src/router/modules/formPemohonAdmin.js, src/router/modules/pengajuanLogistik.js, src/views/permohonan/formPemohon.vue, src/views/permohonan/formPemohonAdmin.vue
Perbaikan penamaan sidebar pengajuan admin dan daftar permohonan alkes.
perbaikan parameter get API master faskes dan master faskes type
=> Perubahan penamaan pengajuan admin dan parameter get faskes

src/views/dashboard/index.vue
=> perbaikan dashboard

src/components/Chart/HorizontalBar.vue, src/components/Chart/applicantInstanceChart.vue, src/components/Chart/statisticApplicantChart.vue, src/components/Chart/toolsTypeChart.vue, src/helpers/formattingNumber.js, src/lang/id.js, src/store/modules/logistics/actions.js, src/store/modules/logistics/getters.js, src/store/modules/logistics/index.js, src/store/modules/logistics/mutations.js, src/views/dashboard/index.vue, src/views/pengajuanLogistik/detail.vue
Pembuatan BarChart Statistik Permohonan Alkes pada Dashboard
=> Dashboard Statistik Permohonan Alkes

src/views/pengajuanLogistik/list.vue
Perbaikan format tanggal pada menu daftar permohonan
=> Perbaikan format tanggal

src/components/Chart/applicantInstanceChart.vue, src/components/Chart/statisticApplicantChart.vue, src/components/Chart/toolsTypeChart.vue, src/components/DatePicker/dateDashboard.vue, src/lang/id.js, src/store/modules/logistics/actions.js, src/views/dashboard/index.vue
Pembuatan fitur filter tanggal pada dashboard
=> Pembuatan fitur filter tanggal pada dashboard

package.json, src/lang/id.js, src/store/modules/logistics/actions.js, src/views/pengajuanLogistik/list.vue
pembuatan fitur export data pada menu daftar permohonan
=> Export data

src/components/Chart/applicantInstanceChart.vue
Perbaikan tambah parameter pada dashboard
=> Perbaikan parameter

src/components/Chart/applicantInstanceChart.vue, src/components/Chart/statisticApplicantChart.vue, src/components/Chart/toolsTypeChart.vue, src/lang/id.js, src/views/dashboard/index.vue, src/views/pengajuanLogistik/list.vue
Perbaikan chart pada menu dashboard dan perbaikan penamaan file download
=> Perbaikan Dashboard dan penamaan file download

src/components/ApplicationForm/AddInstance.vue, src/lang/id.js, src/utils/vee-validate.js
Penambahan input nomor izin sarana pada menu tambah instansi
=> Tambah Input nomor izin sarana

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/ConfirmationStepAdmin.vue, src/components/ApplicationForm/FirstStep.vue, src/store/modules/logistics/actions.js
perubahan dan perbaikan input saat pilih instansi laiinnya atau masyarakat lain
=> Form permohonan alkses perubahan input

src/lang/id.js, src/router/modules/pengajuanLogistik.js, src/views/masterData/faskes/list.vue, src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/list.vue, src/views/pengajuanLogistik/reject.vue
Pemisahan menu pengajuan logsitik menjadi sudah terverifikasi dan belum terverifikasi
pembuatan fitur tolak pengajuan
=> Pemisahan menu pengajuan logistik dan pembuatan fitur tolak

src/views/masterData/faskes/list.vue, src/views/masterData/faskes/verification.vue
Tambah tampiln nomor izin sarana
=> Tambah tampilan nomor izin sarana

src/lang/id.js, src/router/modules/pengajuanLogistik.js, src/views/masterData/faskes/list.vue, src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/list.vue
Pembuatan menu list ditolak
https://trello.com/c/wk03sKD5/94-permohonan-user-dapat-melihat-daftar-permohonan-untuk-status-ditolak
=> Pembuatan menu list ditolak

src/lang/id.js, src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/reasonReject.vue
Pembuatan dialog kebutuhan logistik ditolak
https://trello.com/c/nRbmbUla/91-permohonan-user-dapat-melihat-detail-permohonan-untuk-status-ditolak
=> Pembuatan dialog kebutuhan logistik ditolak

src/router/modules/faskes.js, src/views/masterData/faskes/list.vue, src/views/masterData/faskes/verification.vue, src/views/pengajuanLogistik/list.vue, src/views/pengajuanLogistik/reject.vue
Perbaikan tampilan dialog dan pemisahan 1 sub menu fasilitas kesehatan menjadi ada di tolak
=> Perbaikan tampilan dialog dan pemisahan 1 sub menu fasilitas kesehatan

src/views/pengajuanLogistik/detail.vue
Perbaiakn update pada pengajuan logistik terverifikasi
=> Perbaiakn update pada pengajuan logistik terverifikasi

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/ConfirmationStepAdmin.vue
perbaikan tampilan nama instansi tidak muncul
=> Perbaikan tampilan confirmation step

src/lang/id.js, src/utils/vee-validate.js, src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/reasonReject.vue, src/views/pengajuanLogistik/reject.vue
Perbaikan warna tulisan dan total APD pada dialog tolak
=> Perbaikan warna tulisan dan total APD

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/ConfirmationStepAdmin.vue, src/components/ApplicationForm/FourthStep.vue, src/lang/id.js, src/router/modules/pengajuanLogistik.js, src/store/modules/logistics/actions.js, src/utils/vee-validate.js, src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/list.vue, src/views/permohonan/formPemohon.vue, src/views/permohonan/formPemohonAdmin.vue
Pembuatan fitur list, setujui dan tolak pada menu daftar permohonan telah disetujui dan tambah field nomor permohonan
=> Daftar permohonan tersetujui dan nomor permohonan

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/ConfirmationStepAdmin.vue, src/components/ApplicationForm/FourthStep.vue, src/lang/id.js, src/views/pengajuanLogistik/detail.vue
Menampilkan Nomor Surat pada confirmation step dan detail.
perbaikan bug tampilan dialog
=> Menampilkan 

src/layout/index.vue, src/utils/vee-validate.js, src/views/permohonan/formPemohonAdmin.vue
https://trello.com/c/wojw6GyG/114-permohonan-admin-dapat-melakukan-update-realisasi-permohonan
change validation
=> Change application form

src/layout/index.vue
=> resolve bug staging

src/components/DialogDelete/index.vue, src/lang/id.js, src/store/modules/logistics/actions.js, src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/update.vue
Update and delete realization
https://trello.com/c/o0qI96w6/122-permohonan-admin-dapat-melakukan-tambah-realisasi-distribusi-lainnya-untuk-barang-yang-tidak-ada-pada-permohonan-logistik
=> Realization update

src/views/pengajuanLogistik/detail.vue
Added button back
https://trello.com/c/rsb3uYsL/121-permohonan-memperbaiki-tampilan-detail-permohonan-logistik
=> ApplicationDetail: added button back

src/lang/id.js, src/router/index.js, src/router/modules/letter.js, src/store/index.js, src/store/modules/letter/actions.js, src/store/modules/letter/getters.js, src/store/modules/letter/index.js, src/store/modules/letter/mutations.js, src/views/OutgoingMail/list.vue, src/views/pengajuanLogistik/list.vue
https://trello.com/c/8pDxKt79/116-manajemen-surat-keluar-admin-dapat-melihat-list-surat-keluar
=> Letter list

src/views/OutgoingMail/list.vue
https://trello.com/c/8pDxKt79/116-manajemen-surat-keluar-admin-dapat-melihat-list-surat-keluar
=> LetterList: update button margin and fix date param

src/lang/id.js, src/store/modules/letter/actions.js, src/store/modules/letter/getters.js, src/store/modules/letter/index.js, src/store/modules/letter/mutations.js, src/utils/vee-validate.js, src/views/OutgoingMail/Create.vue, src/views/OutgoingMail/list.vue
https://trello.com/c/R0CLqV7g/115-manajemen-surat-keluar-admin-dapat-membuat-surat-keluar
=> Letter create

src/components/DialogDelete/index.vue, src/lang/id.js, src/router/modules/letter.js, src/store/modules/letter/actions.js, src/store/modules/letter/getters.js, src/store/modules/letter/index.js, src/store/modules/letter/mutations.js, src/views/OutgoingMail/Create.vue, src/views/OutgoingMail/Detail.vue, src/views/OutgoingMail/list.vue
https://trello.com/c/KZxgjk1O/117-manajemen-surat-keluar-admin-dapat-melihat-detail-surat-keluar
=> Letter Detail

src/components/ApplicationForm/ConfirmationStepAdmin.vue, src/components/ApplicationForm/FirstStep.vue, src/components/ApplicationForm/SecondStep.vue, src/views/permohonan/formPemohon.vue, src/views/permohonan/formPemohonAdmin.vue
- Beberapa permohonan ada yang sifatnya direction (langsung dari pimpinan sehingga tidak ada beberapa atribut)
- Form permohonan yang ada pada web admin dilepas beberapa mandatory sehingga beberapa inputan yang tidak perlu diisi, inputan tersebut diantaranya yaitu: 
1. Instansi
- nomor telepon instansi tidak usah
- alamat lengkap tidak usah
2. Pemohon
- jabatan tidak usah
- upload ktp tidak usah
- email pemohon tidak usah
- handphone pemohon minimal satu saja
Detail trello [disini](https://trello.com/c/Ljd9PDsy/182-permohonan-melepas-atribut-mandatory-form-isian-pada-permohonan-web-admin-logistik)
=> Kondisi Permohonan Direktif - Melepas atribut mandatory form isian pada permohonan

src/components/ApplicationForm/SecondStep.vue
debugging `isAdmin` nya masih muncul. Harus dihilangkan sebelum naik ke production
=> Membersihkan debug isAdmin yang masih muncul

src/components/ApplicationForm/AddInstance.vue, src/lang/id.js
- Pemohon dapat melakukan upload surat izin fasyankes, pada form tambah fasyankes
- Upload izin surat fasyankes dapat dilakukan pada form tambah fasyankes yang berada pada web publik (landing page) dan web admin
- Surat izin yang diupload dapat berbentuk pdf ataupun image (jpg, png, jpeg, png)
- Bersifat wajib
trello : https://trello.com/c/nEgaculD/197-tambah-faskes-upload-surat-izin-fasyankes
=> [Tambah Faskes] Upload Surat Izin Fasyankes

src/components/ApplicationForm/AddInstance.vue, src/components/ApplicationForm/FirstStep.vue
temuan :
- tidak bisa menyimpan form fasyankes, muncul error seperti pada gambar berikut,
- saat gagal dan klik tombol ulangi mengarah ke halaman landing page seharusnya halaman form permohonan
- semua form tidak di isi lalu muncul pesan validasi, kemudian klik batal lalu klik form fasyankes kembali, pesan validasi sebelumnya masih muncul
=> [BUGFIX] [Tambah Faskes] Upload Surat Izin Fasyankes

src/components/ApplicationForm/AddInstance.vue, src/components/ApplicationForm/FirstStep.vue
- Saat ini ketika melakukan tambah faskes diarahkan pada halaman landing page baik pada saat ditambahkan pada web publik ataupun pada halaman admin
- **Pada web publik**, seharusnya sesudah menambahkan faskes **diarahkan pada halaman landing page (sudah sesuai)**
- **Pada web admin**, seharusnya ketika sudah menambahkan faskes **diarahkan pada halaman dashboard**
=> [Tambah faskes] Jika tambah faskes sudah ditambahkan untuk web publik diarahkan ke landing page, namun jika di web admin diarahkan ke menu permohonan

src/views/pengajuanLogistik/detail.vue
https://trello-attachments.s3.amazonaws.com/5e7cc257ce91964fe85236ce/5f2a09acac0199248f46bf4e/94bef0f99c2784d0b8a4a2c51046a038/100_.PNG
=> Jika responsif ukuran layar 100%, design berubah menjadi besar dan berantakan

src/lang/id.js, src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/update.vue
[Status Permohonan] Admin dapat melakukan update dan mengganti status barang menjadi "Belum bisa dipenuhi"
**Ditabel Barang**
Di Modal Update Status Barang
=> Penambahan Update Status Barang "Belum Bisa Dipenuhi"

src/lang/id.js, src/utils/validate.js, src/views/pengajuanLogistik/list.vue
- Tambah informasi pada placeholder "Masukkan nomor telepon disertai kode area" 
- Validasi dikurangi menjadi 9 karakter
- Validasi input nomor telepon instansi dilakukan pada form permohonan webadmin (https://logistik.pikobar.jabarprov.go.id/#) dan permohonan publik (https://logistik.pikobar.jabarprov.go.id/#/landing-page)
- card: https://trello.com/c/EBPUbYlX/214-permohonan-memperbaiki-validasi-input-nomortelepon-instansi-pada-form-permohonan-pada-tahap-1-mengisi-identitas-instansi-pemohon
---
- Saat ini kondisi pada list rekomendasi salur dan realisasi masih belum ditandai jika statusnya sudah diselesaikan
- Seharusnya jika sudah diselesaikan ditandai menjadi warna hijau
- Jika yang belum diselesaikan maka ditandai menjadi warna merah
- card: …
=> [Form Permohonan] Memperbaiki Validasi Input Nomor Telepon Instansi & [Daftar Permohonan] Perbaikan Warna PIC jika sudah disetujui/diselesaikan

src/router/modules/letter.js, src/views/InboxMail/detail.vue, src/views/InboxMail/list.vue
Menampilkan detail surat masuk
--------------------------------------
- Detail surat keluar dapat diakses pada list surat masuk dengan memilih salah satu data pada surat masuk
- Tampilan detail surat masuk yang muncul berisi field diantaranya: 
- Tanggal pengajuan
- Status
- Attachment surat permohonan, attachment tersebut dapat dicetak melalui tombol "Unduh"
- Identitas instansi (sama sepeti pada halaman detail permohonan logistik)
Menampilkan daftar kebutuhan logistik (sama sepeti pada daftar permohonan logistik)
--------------------------------------
- Daftar kebutuhan logistik muncul dalam bentuk data table yang berisi field: 
- Nama./ spesifikasi barang
- Deskripsi/ detail
- Jumlah kebutuhan
- Satuan
- Tujuan penggunaan 
- Tingkat urgensi
- Jumlah realisasi
- Tanggal realisasi
- …
=> [Manajemen Surat Masuk] Admin dapat melihat detail surat permohonan masuk

src/lang/id.js, src/store/modules/logistics/actions.js, src/store/modules/logistics/getters.js, src/store/modules/logistics/index.js, src/store/modules/logistics/mutations.js, src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/stock.vue, src/views/pengajuanLogistik/update.vue
- Pada saat cek stok barang dengan item permohonan Reagent dan VTM perlu ditambahkan dengan data spreadsheet dari Labkesda
- Perubahan acuan API untuk data GUDANG LABKES ke API Dashboard Eksekutif
- link Trello: https://trello.com/c/39OarAsv/211-cek-stok-cek-stok-barang-untuk-data-spreadsheet-dari-labkes-dengan-item-reagent-dan-vtm
=> [BUGFIX] [Cek Stok] Cek stok barang untuk data spreadsheet dari labkes dengan item Reagent dan VTM

src/store/modules/logistics/actions.js, src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/list.vue, src/views/pengajuanLogistik/update.vue
- Debug Limit List Barang max 3 per halaman
- Set Loading Process, Format Currency, dan Format Tanggal
- Debug Limit List Barang max 3 per halaman
=> Bug Fix Minor Sebelum Naik v1.1.9

README.md, src/components/Chart/applicantInstanceChart.vue, src/components/Chart/statisticApplicantChart.vue, src/components/Chart/toolsTypeChart.vue, src/helpers/formattingNumber.js, src/views/dashboard/index.vue, src/views/pengajuanLogistik/detail.vue, src/views/tracking/index.vue
Atribut yang muncul pada daftar list permohonan yang disalurkan diantaranya yaitu:
Pada bagian Permohonan:
- Nama barang
- Deskripsi
- Jumlah
- Satuan
- Jenis Barang
Pada bagian Rekomendasi:
- Nama barang
- Jumlah
- Satuan
- Status
Pada bagian Realisasi:
- Nama barang
- Jumlah
- Satuan
- Status
**Tabel Barang di Halaman Tracking**
**Formatting Number di Halaman Dashboard**
=> Pengembangan Halaman Tracking & Formatting Number di Dashboard di v1.1.10

src/lang/id.js, src/store/modules/letter/actions.js, src/utils/vee-validate.js, src/views/OutgoingMail/Create.vue, src/views/OutgoingMail/Detail.vue, src/views/OutgoingMail/Upload.vue, src/views/OutgoingMail/list.vue
- Admin dapat melakukan upload surat perintah melalui button yang ada pada halaman daftar surat keluar
- Ketika tombol surat keluar diklik akan muncul popup yang berisi isian nomor surat perintah (pencarian nomor surat keluar) dan upload surat perintah yang sudah ditandatangani
- Jika sudah diupload, maka file tersimpan dan status surat perintah akan berubah menjadi "Sudah tanda tangan basah" 
- Admin dapat mengunduh surat yang ditandatangani
- Jika sudah diupload surat perintah yang sudah ditanda tangan basah, maka surat sebelumnya (yang belum ditanda tangan) akan ditimpa dengan surat yang sudah ditanda tangani
=> [Surat Perintah] Admin dapat melakukan upload surat perintah yang sudah diberi nomor dan ditanda tangani

src/views/pengajuanLogistik/agencyIdentity.vue, src/views/pengajuanLogistik/applicantIdentity.vue, src/views/pengajuanLogistik/updateLetter.vue
- Bug Fix Nama Faskes tidak muncul di list edit
- Email pemohon tidak muncul di form edit data pemohon
- Perbaikan Label yang salah acuan
- Menghilangkan Pengkondisian isAdmin di Dialog Update Identitas Instansi
- Trello Card: [link](https://trello.com/c/y3GDiRFS/242-issue-edit-detail-pengajuan-logistik)
=> Bug Fix Edit Detail Permohonan

src/lang/id.js, src/store/modules/logistics/actions.js, src/views/pengajuanLogistik/updateLetter.vue
- Perbaikan Header dialog Edit Surat Permohonan
- judul edit surat permohonan seharusnya "Edit Permohonan - Surat Permohonan"
- Bug Fix Klik Edit Surat Permohonan
- Saat klik Edit Surat Permohonan, Surat yang sudah diupload sebelumnya harusnya dimunculkan
- Reset Dialog ketika klik button Edit Surat Permohonan
- jika belum upload surat permohonan muncul pesan error, lalu klik batal kemudian saat klik edit kembali pesan error masih muncul
=> Bug fix edit surat permohonan v2

src/views/pengajuanLogistik/applicantIdentity.vue, src/views/pengajuanLogistik/completenessDetail.vue, src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/list.vue
=> Change fix v1112

src/components/ApplicationForm/ThirdStep.vue, src/lang/id.js, src/utils/vee-validate.js, src/views/pengajuanLogistik/detail.vue
1. Validasi tidak boleh desimal di tahap 3 buat permohonan
2. Error Fix agency_id not found
=> Bug Fix Buat Permohonan

src/lang/id.js, src/layout/Sidebar/SidebarItem.vue, src/views/OutgoingMail/list.vue, src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/list.vue
- seharusnya menggunakan ID Agency di parameter yang dikirimkan
- [Menu Utama] Redaksi Pengajuan Logistik dan Manajemen Surat ditampilkan penuh tidak muncul sebagian
=> Bug ID di Fitur Mengembalikan Tahapan Permohonan

src/store/modules/logistics/actions.js, src/views/pengajuanLogistik/agencyIdentity.vue, src/views/pengajuanLogistik/applicantIdentity.vue, src/views/pengajuanLogistik/updateLetter.vue
- Error ketika edit permohonan bagian Identitas pemohon
- Error ketika edit permohonan bagian surat permohonan
[v1.1.14]
=> Fix Error edit permohonan

src/lang/id.js, src/store/modules/user/actions.js, src/views/OutgoingMail/Detail.vue, src/views/changePassword/index.vue, src/views/pengajuanLogistik/list.vue, src/views/pengajuanLogistik/referenceDetail.vue
- Cetak Surat Perintah seharusnya format PDF
- Menambahkan kolom tipe instansi
- PopUp keterangan RS Rujukan
- Perbaikan Fitur Ganti Password
=> Perbaikan Bug Cetak Surat Perintah, Pengembangan RS Rujukan & Fitur Ganti Password

src/lang/id.js
Revisi Judul Buat Permohonan tahap ke 4
=> [HOTFIX] Revisi Judul Buat Permohonan tahap ke 4

src/components/ApplicationForm/AddInstance.vue, src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/ConfirmationStepAdmin.vue, src/components/ApplicationForm/FourthStep.vue, src/components/ApplicationForm/SecondStep.vue, src/lang/id.js, src/views/acceptanceReport/index.vue, src/views/landingPage/index.vue, src/views/permohonan/formPemohon.vue, src/views/permohonan/formPemohonAdmin.vue
1. Pemasangan Link Form Laporan Penggunaan Logistik
2. Menghilangkan Pemanggilan Duplicate ke API master faskes type
3. [Bug] Validasi Upload KTP di Permohonan https://trello.com/c/hvCcgPYv/290-bug-validasi-upload-ktp-di-permohonan
4. Hapus Identitas Pemohon Landing Page https://trello.com/c/hvCcgPYv/290-bug-validasi-upload-ktp-di-permohonan
5. Hapus Identitas Pemohon KTP/Kartu Pegawai/Surat Tugas https://trello.com/c/hvCcgPYv/290-bug-validasi-upload-ktp-di-permohonan
6. Surat Permohonan hanya extension .pdf
7. Error Fix Buat Permohonan Tahap 4 via Admin
8. Hide Button Isi Default Form ketika di server staging / production
9. Error Fix Buat Permohonan Tahap 4 via Landing Page
=> [Bug] Validasi Upload KTP di Permohonan

src/lang/id.js, src/views/acceptanceReport/index.vue, src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/update.vue
1. Detail Permohonan - Bug Edit Daftar Barang Rekomendasi Salur
2. Detail Permohonan - Realisasi - bug Hapus daftar realisasi oleh admin https://trello.com/c/4FIS82dU/294-bug-hapus-daftar-barang-rekomendasi-salur-lainnya-menu-realisasi-tidak-langsung-kembali-ke-menu
3. Edit Daftar Barang - Itu tidak muncul satuannya https://trello.com/c/Wcq7XTms/296-bug-edit-daftar-barang-rekomendasi-salur-lainnya-menu-realisasi
4. Pelaporan Permintaan Barang - Bug Error Date is null https://trello.com/c/vaOQ1T2R/256-pelaporan-pemohon-dapat-mengisi-form-pelaporan-penerimaan-barang
5. Pelaporan Permintaan Barang - tambah kolom 'Catatan Lainnya'
6. Detail Permohonan - button `Selesaikan` tidak ada respon https://trello.com/c/I1kuBsjD/295-bug-tidak-dapat-selesaikan-permohonan-di-realisasi-salur-tidak-ada-resp …
=> Bug Fix v1.1.17.2

src/lang/id.js, src/views/pengajuanLogistik/agencyIdentity.vue, src/views/pengajuanLogistik/applicantIdentity.vue, src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/dialogReturn.vue, src/views/pengajuanLogistik/dialogUrgency.vue, src/views/pengajuanLogistik/update.vue, src/views/pengajuanLogistik/updateLetter.vue
1. Ubah Data Instansi di Permohonan - Penambahan Param agency_id
2. Ubah Data Pemohon di Permohonan - Penambahan param agency_id
3. Ubah Data Surat Permohonan - penambahan param agency_id
4. Verifikasi Permohonan - penambahan param agency_id
5. Tolak Verif Permohonan - Verifikasi Permohonan - penambahan agency_id
6. Setujui Permohonan - Verifikasi Permohonan - penambahan param agency_id
7. Selesaikan Permohonan - Verifikasi Permohonan - penambahan agency_id
8. Ubah Urgensi Permohonan - Kondisi tambah applicant_id & agency_id
9. Fitur Mengembalikan status permohonan - tambah agency_id & applicant_id
10. Pemasangan fitur loading ketika sedang mengubah data permohonan
11. Proses Loading ketika dialog Update dipanggil
12. FIX - satuan yang dipilih tidak terselect otomatis di dialog update
13. …
=> Penambahan param ketika modifikasi permohonan

src/store/modules/logistics/actions.js, src/views/acceptanceReport/index.vue
https://trello.com/c/zybbmpfX/301-penerimaan-barang-kirim-ulang-kode
=> Fitur Kirim Ulang Kode Verifikasi ke email

src/components/ApplicationForm/FourthStep.vue, src/views/acceptanceReport/index.vue, src/views/tracking/index.vue
=> Pre up to v17

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/ConfirmationStepAdmin.vue, src/components/ApplicationForm/FirstStep.vue, src/components/ApplicationForm/FourthStep.vue, src/components/ApplicationForm/SecondStep.vue, src/components/ApplicationForm/ThirdStep.vue, src/views/pengajuanLogistik/detail.vue, src/views/permohonan/formPemohon.vue, src/views/permohonan/formPemohonAdmin.vue, src/views/tracking/index.vue
=> Pre up to v18

src/components/DatePicker/dateDashboard.vue, src/components/Pagination/index.vue, src/views/InboxMail/detail.vue, src/views/InboxMail/list.vue, src/views/OutgoingMail/Detail.vue, src/views/OutgoingMail/Upload.vue, src/views/OutgoingMail/list.vue, src/views/pengajuanLogistik/detail.vue, src/views/pengajuanLogistik/list.vue
Ada isu dihalaman yang menggunakan komponen pagination kalau angka di paginationnya hilang. seharusnya muncul. Isu ini ada di halaman Daftar Permohonan Logistik, Daftar Surat Perintah dan Daftar Surat Masuk
Contoh seperti tampilan pada gambar di bawah ini.
ini tampilan pagination di halaman 3. seharusnya angka 3 muncul di pagination ini.
ternyata, komponen pagination di masing-masing file `list.vue` nya menggunakan `v-row` yang menyebabkan terdempetnya pagination yang seharusnya muncul angkanya, bukan titik-titik.
- menghilangkan baris yang menggunakan v-row dan menggantinya dengan code yang memanggil komponen pagination.
- memindahkan info total data ke atas tabel daftar datanya.
=> Fixing Halaman yang menggunakan Pagination

src/components/Pagination/index.vue, src/views/InboxMail/list.vue, src/views/OutgoingMail/list.vue, src/views/masterData/faskes/list.vue, src/views/pengajuanLogistik/list.vue
- Penambahan filterisasi berdasarkan Rujukan. Pilihannya ada 3: yaitu:
- Rujukan
- Bukan Rujukan
- Semua (Tidak dipilih apapun)
- Mengirimkan parameter `is_reference` yang berisikan nilai 1 (Rujukan), 0 (Bukan Rujukan) dan tidak mengirimkan parameter (Semua ditampilkan)
- Perbaikan Fitur Pagination
- Memindahkan fitur menampilkan total data keseluruhan di component pagination
- mengkondisikan fitur total data agar tidak muncul apabila tidak dikirimkan oleh suatu halaman
- Memindahkan fitur total Data Daftar Surat Perintah ke pagination
- Memindahkan fitur total Data Daftar Surat Masuk ke pagination
- Perbaikan Error Console `clearable must boolean, not string` di halaman Daftar Faskes
=> Daftar Permohohan Logistik - Fitur Filterisasi Berdasarkan Rujukan

Jenkinsfile.jacloud, kubernetes/deployment-logistik.yaml, kubernetes/service-logistik.yaml
bismillah
inisiasi migrasi compute pikobar-logistik-frontend dari docker-compose ke k8s di jabarcloud
=> Devops jabar cloud

src/views/tracking/index.vue
- Bugfix Loading Pending tidak kunjung selesai di staging
- Perbaikan [Vue warn]: You may have an infinite update loop in a component render function
=> Tracking - Perbaikan Warning Console Loop Function or Components

src/views/reports/goods_receipt_report/list.vue
Pencarian data dapat dilakukan dengan memasukkan keyword `string` berupa kode permohonan ataupun nama pemohon.
- keyword adalah parameter `search`
- Kode permohonan adalah `agency.id`
- nama pemohon adalah `applicants.applicant_name`
- menghilangkan `status`
- menghilangkan `applicantOrigin`
- menghilangkan `referenceFaskes`
- menghilangkan `completeStatus`
- menghilangkan `urgencyStatus`
- menghilangkan `finalizedStatus`
- menghilangkan pengkondisian `status` di `created()`
- mengganti nama method dari `getLogisticRequestList()` menjadi `getAcceptanceReportList()`
- mengubah variabel `listQuery`:
- menghilangkan `sort`
- menghilangkan `city_code`
- menghilangkan `verification_status`
- menghilangkan `agency_name`
- menghilangkan `start_date`
- menghilangkan `end_date`
- menghilangkan …
=> [Laporan penerimaan] Admin dan PIC dapat melakukan pencarian data laporan penerimaan logistik

src/lang/id.js, src/router/modules/reports.js, src/store/modules/logistics/actions.js, src/store/modules/logistics/getters.js, src/store/modules/logistics/index.js, src/store/modules/logistics/mutations.js, src/views/acceptanceReport/index.vue, src/views/reports/goods_receipt_report/detail.vue, src/views/reports/goods_receipt_report/list.vue
- Detail laporan penerimaan logistik dapat diakses melalui daftar laporan penerimaan logistik dengan memilih salah satu penerimaan logistik
- Detail dapat dilihat oleh admin dan PIC baik permohonan yang sudah lapor atau belum
- Data yang ditampilkan pada detail penerimaan logistik jika status penerimaan sudah lapor diantaranya: 
- Kode Permohonan
- Nama pemohon
- Status (sudah lapor/ belum lapor)
- Detail Penerimaan Barang
- Daftar Item Barang yang Diterima
- Foto Bukti Penerimaan Barang
- Foto BAST Penerimaan Barang
- Lainnya (berisi catatan pemohon terhadap kondisi penerimaan barang)
- Data yang ditampilkan pada detail penerimaan logistik jika status penerimaan belum lapor diantaranya: 
- Kode Permohonan
- Nama pemohon
- Status (sudah lapor/ belum lapor)
- Detail Penerimaan Barang
- …
=> 2148 - Admin dan PIC dapat melihat detail laporan penerimaan logistik yang diterima pemohon

src/lang/id.js, src/views/acceptanceReport/index.vue, src/views/reports/goods_receipt_report/detail.vue
- Penambahan Isian Testimoni
- Pengkondisian format file yang bisa diupload hanya `.jpg`, `.jpeg`, `.png`
- Menambahkan Detil Testimoni
=> Laporan Penerimaan Logistik - Penambahan Feedback di Form & Detil, dan pengkondisian form file yang bisa diupload user

src/components/Statistic/StatisticCard.vue, src/lang/id.js, src/store/modules/logistics/actions.js, src/store/modules/logistics/getters.js, src/store/modules/logistics/index.js, src/store/modules/logistics/mutations.js, src/views/reports/goods_receipt_report/list.vue
1. Create statistic card component
2. Display statistic card on report page
https://trello.com/c/qIaYHsgl/357-2145-laporan-penerimaan-sp-1-admin-dan-pic-dapat-melihat-statistik-permohonan-yang-sudah-melaporkan-dan-belum-melaporkan
- Before
- After
cc: @Arif9878 @adrianpdm @maruf12 @adzharamrullah @Ibwedagama @bangunbagustapa @maulanayuseph @yoslie
=> Feature Receipt Statistic

src/components/DatePicker/dateDashboard.vue, src/lang/id.js, src/views/reports/goods_receipt_report/list.vue
1. Create filter component
2. Fix ranged date picker component layout
https://trello.com/c/o3eAZqGQ/353-2146-laporan-penerimaan-sp2-admin-dan-pic-dapat-melakukan-filter-tanggal-barang-diterima-dan-status-permohonan-yang-sudah-lapor
- Before
- After
cc: @Arif9878 @adrianpdm @maruf12 @adzharamrullah @Ibwedagama @bangunbagustapa @maulanayuseph @yoslie
=> Feature Receipt Filter

src/views/pengajuanLogistik/detail.vue
- Prevent Kota/Kab user to do `write` actions
https://trello.com/c/Y9OwwKZv/407-2513-akses-dinkes-kab-kota-dinkes-dapat-melihat-pengajuan-berdasarkan-tahapannya-yang-difilter-berdasarkan-kota-tempat-dinkes-ko
=> Hide all actions in detail for user Kota/Kab

src/components/Chart/applicantInstanceChart.vue, src/components/Chart/summaryChart.vue, src/components/Chart/toolsTypeChart.vue, src/store/modules/logistics/actions.js, src/views/dashboard/index.vue, src/views/reports/goods_receipt_report/list.vue
Add `city_code` param for Kota/Kab users
https://trello.com/c/oanS45rz/406-2512-akses-dinkes-kab-kota-sp2-dinkes-dapat-melihat-dashboard-berdasarkan-kota-kabupaten-user-login
=> Add param city_code for Kota/Kab users

src/views/pengajuanLogistik/detail.vue
https://trello.com/c/DO4917gk/410-permohonan-pembuatan-exception-ketika-pengguna-menembak-langsung-id-permohonan-pada-url
=> Prevent unauthorized user access detail page

src/views/pengajuanLogistik/detail.vue
Fix width button when case is being done
=> Fix width done button

src/views/pengajuanLogistik/detail.vue
Fix responsive layout for detail page
https://trello.com/c/RIxFt6Gz/411-perbaikan-layout-halaman-detail
Before             |  After
:-------------------------:|:-------------------------:
=> Fix responsive layout

src/views/pengajuanLogistik/detail.vue
Make width some column fixed
https://trello.com/c/RIxFt6Gz/411-2167-perbaikan-dan-bug-fixing-sp-1-perbaikan-layout-halaman-detail
=> Fix width column in detail page

src/lang/id.js, src/views/tracking/status.vue
1. Translate status value
2. Change `store-cp` width
https://trello.com/c/PMuCGTtD/418-2168-tracking-sp-13-mengubah-tampilan-halaman-tracking-permohonan-logistik
=> Change Status Display Value

src/views/tracking/status.vue
Fix recommendation status label
https://trello.com/c/PMuCGTtD/418-2168-tracking-sp-13-mengubah-tampilan-halaman-tracking-permohonan-logistik
=> Fix translate recommendation status

src/views/tracking/index.vue
When this page is accessed for the first time, it'll reload after pressing enter to submit form
=> Fix auto reload page when submitting form

.gitignore, sonar-project.properties.example
Add `sonar-project.properties.example` file and update `.gitignore`
=> Add SonarScanner Example File

src/views/pengajuanLogistik/list.vue
https://trello.com/c/PFUt9jMs/429-issue-tanggal-pengajuan-tertulis-17-juni-2021-kesemuanya-hotfix
=> Fix created_at column

package.json, src/views/pengajuanLogistik/list.vue
https://github.com/jabardigitalservice/pikobar-logistik-frontend/pull/281
=> [Bug Fix] Up To Production v1.2.3c - Wrong value for `Tanggal Pengajuan` column

src/views/tracking/status.vue
https://trello.com/c/9Rpb1yKw/430-issue-pada-tracking-tidak-muncul-alasan-penolakan-alasan-penolakan-muncul-pada-step-verifikasi-ditolak-dan-rekomendasi-ditolak
=> Add rejection note alert

src/views/tracking/status.vue
Step 2 will active when recommendation data is not null or there is some rejection note
=> Add rejection note condition in step two tracking

src/views/tracking/index.vue
Undo deletion of `keyup.enter.native` in `v-text-field`
=> Fix auto reload tracking form

src/lang/id.js, src/router/modules/pengajuanLogistik.js, src/views/dashboard/index.vue, src/views/pengajuanLogistik/list.vue
1. Split menu `Realisasi` into `Belum Realisasi` and `Selesai Realisasi`
2. Delete `finalized_by` filter on both page
https://trello.com/c/jTkGHiE7/452-2172-menu-realisasi-salur-pembuatan-menu-belum-salur
https://trello.com/c/V20T6rnj/453-2173-menu-realisasi-salur-pembuatan-menu-selesai-salur
=> Split menu Realisasi

src/lang/id.js, src/router/modules/reports.js, src/store/index.js, src/store/modules/allocation/actions.js, src/store/modules/allocation/index.js, src/store/modules/allocation/mutations.js, src/views/reports/allocation/AllocationFilter.vue, src/views/reports/allocation/AllocationTable.vue, src/views/reports/allocation/list.vue, src/views/reports/allocation/tableHeader.js
1. Create page allocation
2. Create `allocation` vuex module
https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwittlbwGyGABPNQ/recMQXgoChDbFmAlA?blocks=hide
title: Code Review Create Allocation Page
participants: @maulanayuseph @adzharamrullah @Arif9878 @Ibwedagama @bangunbagustapa @ihsannaufalk
=> Create Allocation Page

src/views/reports/allocation/AllocationFilter.vue, src/views/reports/allocation/list.vue
1. emit changes date value from `AllocationFilter` component
2. change `success` and `draft` dropdown value
https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwittlbwGyGABPNQ/recbXBVnAJsuVEDW5?blocks=hide
=> Filter component adjustment

src/components/DropdownInput/index.vue, src/lang/id.js, src/store/modules/allocation/index.js, src/views/allocation/form/StepTwo.vue, src/views/allocation/form/StepTwoChild.vue, src/views/allocation/form/StepTwoParent.vue, src/views/allocation/form/form.vue, src/views/allocation/form/stepOneField.js, src/views/allocation/form/stepTwoField.js
1. Create `allocationForm` in `allocation` vuex module
2. Create dummy `StepTwoParent` and `StepTwoChild` components (revamp)
title: Revamp Allocation Form Step Two
participants: @naufalihsank @maulanayuseph @maruf12 @bangunbagustapa @Ibwedagama
=> Revamp Allocation Form Step Two

src/views/allocation/form/StepTwo.vue
title: Fix allocation step two add instance
participants: @naufalihsank @maruf12 @bangunbagustapa @Ibwedagama @adzharamrullah
=> Fix allocation step two add instance

src/components/DropdownInput/index.vue, src/store/index.js, src/store/modules/allocation/index.js, src/store/modules/vaccine/actions.js, src/store/modules/vaccine/index.js, src/store/modules/vaccine/mutations.js, src/views/allocation/form/StepTwo.vue, src/views/allocation/form/StepTwoChild.vue, src/views/allocation/form/StepTwoParent.vue, src/views/allocation/form/stepTwoField.js
1. implement real data for instance list input options
2. add `itemText`, `itemValue`, and `disabled` props in `DropdownInput` component
3. initiate `vaccine` vuex module
title: Instance list options in allocation form step two
participants: @naufalihsank @adzharamrullah @Ibwedagama @bangunbagustapa @yoslie
=> Instance list options in allocation form step two

src/components/requestVaccine/list.vue, src/router/modules/requestVaccine.js
Preview:
- added sample detail vaccine request
Related: 
https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwittlbwGyGABPNQ/rec4P9PB7XZMfyOqO?blocks=bipBVobkbQcj0ovZ8
Evidence
Project: Pikobar Logistik
Title: Add detail vaccine request
Participants: @maruf12, @naufalihsank, @bangunbagustapa, @Ibwedagama, @maulanayuseph
=> added sample detail for vaccine request

src/components/DatePicker/dateDashboard.vue, src/components/requestVaccine/searchFilter.vue
Preview:
- Fixing placeholder on search input field
- Fixing start date filter. Set default to 2021
Related:
https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwittlbwGyGABPNQ/recaBvvqnMXTrF1Db?blocks=bipBVobkbQcj0ovZ8
Evidence
Project: Pikobar Logistik
Title: Fixing filter on list vaccine request
Participants: @maruf12, @maulanayuseph, @adzharamrullah, @bangunbagustapa
=> fixing filter vaccine request

src/components/DatePicker/index.vue, src/components/DropdownInput/index.vue, src/views/allocation/form/StepTwo.vue, src/views/allocation/form/StepTwoChild.vue, src/views/allocation/form/StepTwoParent.vue, src/views/allocation/form/form.vue, src/views/allocation/form/stepTwoField.js
As described on PR title
title: Allocation form step two validation 
participants: @naufalihsank
=> Allocation form step two validation 

src/lang/id.js, src/store/modules/allocation/index.js, src/views/allocation/detail/detail.vue, src/views/allocation/form/StepThree.vue, src/views/allocation/form/StepTwo.vue, src/views/allocation/form/StepTwoParent.vue
1. store `agency_type_name` in `allocationForm` state
2. create Allocation Form Step Three component
title: Allocation form step three
participants: @naufalihsank @Ibwedagama @yoslie @bangunbagustapa @adzharamrullah
=> Allocation form step three

src/lang/id.js, src/router/index.js, src/router/modules/otherInstance.js, src/store/modules/faskes/actions.js, src/store/modules/faskes/getters.js, src/store/modules/faskes/index.js, src/store/modules/faskes/mutations.js, src/views/masterData/faskes/list.vue, src/views/masterData/instance/dataTable.vue, src/views/masterData/instance/list.vue, src/views/masterData/instance/searchFilter.vue
Review:
- Added list other instance
Related:
https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwittlbwGyGABPNQ/recvm66x9tVVuoSqU?blocks=bipBVobkbQcj0ovZ8
Evidence
title: Add list other instance
participants: @maruf12
=> List new faskes

src/components/DatePicker/index.vue, src/lang/id.js, src/views/allocation/form/StepThree.vue, src/views/allocation/form/StepThreeDetail.vue
1. add applicant info in step three
2. disable all `date-picker` component to input manually
title: Applicant info in step three allocation form
participants: @naufalihsank @yoslie @bangunbagustapa @maulanayuseph @adzharamrullah
=> Applicant info in step three allocation form

src/lang/id.js, src/views/masterData/instance/add.vue, src/views/masterData/instance/dataTable.vue, src/views/masterData/instance/list.vue
Preview:
- Redesign list instance
Related:
https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwittlbwGyGABPNQ/rec4QeMj74XDisiGN?blocks=bipBVobkbQcj0ovZ8
Evidence
title: Redesign list instance
participants: @maruf12
=> Redesign table list instance

sonar-project.properties.example, src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/FirstStep.vue, src/components/ApplicationForm/FourthStep.vue, src/components/ApplicationForm/SecondStep.vue, src/components/ApplicationForm/ThirdStep.vue, src/components/Chart/toolsTypeChart.vue, src/layout/Header/Header.vue, src/layout/Sidebar/SidebarItem.vue, src/router/modules/allocation.js, src/router/modules/dashboard.js, src/router/modules/distribusiRdt.js, src/router/modules/formPemohonAdmin.js, src/router/modules/masterData.js, src/views/OutgoingMail/Create.vue, src/views/OutgoingMail/Upload.vue, src/views/OutgoingMail/list.vue, src/views/landingPage/index.vue, src/views/pengajuanLogistik/list.vue, src/views/permohonan/formPemohon.vue, src/views/permohonan/formPemohonAdmin.vue, tests/unit/coverage/components/HelloWorld.vue.html, tests/unit/coverage/lcov-report/base.css, tests/unit/coverage/lcov-report/components/HelloWorld.vue.html
- Delete unnecessary code to improve sonar qube's  code smell
- Code smell score improved from `428` to `100`
title: Code Smell Improvement
participants: @naufalihsank @maulanayuseph @adzharamrullah @Ibwedagama @yoslie
=> Code Smell Improvement

src/views/requestVaccine/detail.vue
- Stock Check Feature add filtering condition
- Finalizing Vaccine Request and Send to WMS Poslog Vaccine
title: Ready to Integrate Vaccine Request to WMS Poslog
participants: @rindibudiaramdhan @Ibwedagama @naufalihsank @yoslie @bangunbagustapa @maulanayuseph 
cc: @jabardigitalservice/jds-frontend
=> Ready to Integrate Vaccine Request to WMS Poslog

src/components/requestVaccine/list.vue
title: fix route name condition
participants: @naufalihsank @maulanayuseph @Ibwedagama @doohanas
=> fix route name condition

src/components/requestVaccine/dataTable.vue
title: fix header in vaccine table
participants: @naufalihsank @maruf12 @rindibudiaramdhan @bangunbagustapa
=> fix header in vaccine table

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/ThirdStep.vue
[[Bug] Seharusnya permohonan logistik vaksin baru tidak masuk ke daftar permohonan logistik alkes](https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwittlbwGyGABPNQ/recYSwumOTCJmqtvH?blocks=hide)
title: Fix submit endpoint and dropdown list
participants: @naufalihsank @maulanayuseph @maruf12 @bangunbagustapa @yoslie
=> Fix submit endpoint and dropdown list

src/components/ApplicationForm/ConfirmationStep.vue
title: add 201 status option in success condition
participants: @naufalihsank @maulanayuseph @bangunbagustapa @rindibudiaramdhan
=> add 201 status option in success condition

src/components/ApplicationForm/ThirdStep.vue, src/components/ApplicationForm/ThirdStepItem.vue
title: Refactor third step of request form
participants: @naufalihsank @maulanayuseph @Ibwedagama @bangunbagustapa
=> Refactor third step of request form

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/FirstStep.vue, src/components/ApplicationForm/ThirdStep.vue, src/components/ApplicationForm/ThirdStepItem.vue, src/components/ApplicationForm/VaccineSupporterInput.vue, src/store/modules/faskes/actions.js, src/store/modules/faskes/index.js, src/store/modules/faskes/mutations.js, src/store/modules/faskesType/actions.js, src/store/modules/faskesType/index.js, src/store/modules/faskesType/mutations.js, src/store/modules/logistics/actions.js, src/store/modules/logistics/index.js, src/store/modules/logistics/mutations.js
Adjust
1. `Jenis instansi`
2. `Nama Instansi`
3. `Nama Barang Vaksin`
4. `Nama Barang Penunjang Vaksin`
dropdown options list in third step form
[Sebagai pemohon dapat mengisi item barang permohonan vaksin dan logistik pendukung vaksin](https://app.clickup.com/t/27jf27v)
title: Adjust dropdown list
participants: @naufalihsank @maulanayuseph @adzharamrullah @Ibwedagama @bangunbagustapa @yoslie
=> Adjust dropdown list from API

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/FirstStep.vue, src/components/ApplicationForm/FourthStep.vue, src/components/ApplicationForm/ThirdStepItem.vue
title: Request form payload adjustment
participants: @naufalihsank @maulanayuseph @maruf12 @adzharamrullah @Ibwedagama @bangunbagustapa @yoslie
=> Request form payload adjustment

src/components/ApplicationForm/ThirdStep.vue, src/components/ApplicationForm/ThirdStepItem.vue, src/components/ApplicationForm/VaccineSupporterInput.vue
title: Revamp Request Form
participants: @naufalihsank @maulanayuseph @Ibwedagama @yoslie
=> create purpose dropdown for vaccine form input

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/VaccineSuccess.vue, src/store/modules/logistics/index.js, src/views/permohonan/formPemohon.vue
1. change formType to url query type
2. add copied success message in tooltip component
3. create letter download button
title: Fix Request Form Issue
participants: @naufalihsank @maulanayuseph @adzharamrullah @bangunbagustapa
=> Fix Request Form Issue

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/FirstStep.vue, src/components/ApplicationForm/ThirdStep.vue, src/store/modules/logistics/actions.js, src/store/modules/logistics/mutations.js, src/views/landingPage/index.vue, src/views/landingPageVaccine/RequirementPopUp.vue
title: set request form url query
participants: @naufalihsank @maulanayuseph @adzharamrullah @Ibwedagama @yoslie
=> Replace formType vuex state into url query

src/components/Base/JDSButton/index.vue, src/components/Base/JDSTable/index.vue, src/components/Base/SearchInput/index.vue, src/helpers/tableDisplay.js, src/lang/id.js, src/plugins/vuetify.js, src/views/immunization/adminVerification/index.vue
1. create base jds button component
2. create base jds table component
3. create base jds search input component
4. create admin verification page
[[Verifikasi Permohonan] Sebagai PIC dapat melihat daftar permohonan dalam tahapan verifikasi](https://app.clickup.com/t/2b4y5b3)
title: Page Admin Verification
participants: @naufalihsank @maulanayuseph @adzharamrullah @Ibwedagama @bangunbagustapa @yoslie
=> Page Admin Verification

src/lang/id.js, src/views/immunization/detail/RequestTableSection.vue, src/views/immunization/detail/index.vue
title: Rename table section component
participants: @naufalihsank @maulanayuseph @yoslie
=> Rename table section component

src/components/Base/JDSTable/index.vue, src/lang/id.js, src/router/modules/vaccine/immunization.js, src/views/immunization/detail/ActionButton.vue, src/views/immunization/detail/RecommendationTableSection.vue, src/views/immunization/detail/index.vue, src/views/immunization/recommendation/index.vue
title: Recommendation Detail Page
participants: @naufalihsank @maulanayuseph @Ibwedagama @bangunbagustapa
=> Create Recommendation Detail Page

src/lang/id.js, src/layout/Sidebar/SidebarItem.vue, src/router/index.js, src/router/modules/vaccine/pharmacy.js, src/views/immunization/recommendation/index.vue, src/views/pharmacy/realization/index.vue
1. setup sidebar to display menu item which has 1 child
2. create pharmacy module in sidebar menu
3. create realization page
[[Realisasi Salur] Sebagai PIC Farmasi dapat melihat daftar permohonan dalam tahapan Realisasi Salur](https://app.clickup.com/t/2fzcjtb)
title: Realization Page
participants: @naufalihsank @adzharamrullah @bangunbagustapa
=> Realization Page

src/lang/id.js, src/router/index.js, src/router/modules/vaccine/logisticPost.js, src/views/immunization/adminVerification/index.vue, src/views/logisticPost/deliveryPlan/index.vue
create delivery plan page
[[Rencana Pengiriman] Sebagai PIC Poslog dapat melihat daftar rencana pengiriman](https://app.clickup.com/t/2g51wyg)
title: Delivery Plan Page
participants: @naufalihsank @Ibwedagama @bangunbagustapa @yoslie
=> Delivery Plan Page

src/views/immunization/detail/Dialog.vue
title: Refactor dialog component
participants: @naufalihsank @maulanayuseph @Ibwedagama @yoslie
=> Refactor dialog component

src/views/immunization/detail/index.vue
title: fix status value
participants: @naufalihsank @maulanayuseph @adzharamrullah @bangunbagustapa
=> fix status value

src/lang/id.js, src/router/modules/vaccine/pharmacy.js, src/views/immunization/detail/ActionButton.vue, src/views/immunization/detail/RealizationTableSection.vue, src/views/immunization/detail/index.vue, src/views/pharmacy/realization/index.vue
[[Realisasi Salur] Sebagai PIC Farmasi dapat melihat detail permohonan dalam tahapan Realisasi Salur](https://app.clickup.com/t/2fzcjxg)
title: realization detail page
participants: @naufalihsank @Ibwedagama @bangunbagustapa
=> Create realization detail page

src/components/Base/JDSSelect/index.vue
title: jds dropdown component
participants: @naufalihsank @maulanayuseph @yoslie
=> Create jds dropdown component

src/lang/id.js, src/router/modules/vaccine/immunization.js, src/views/immunization/detail/RecommendationTableSection.vue, src/views/immunization/update/RecommendationSection.vue, src/views/immunization/update/RequestSection.vue, src/views/immunization/update/index.vue
create recommendation update page with dummy data
[[Rekomendasi Salur] Sebagai PIC Imunisasi dapat melakukan Update Rekomendasi Vaksin](https://app.clickup.com/t/2fzcbk6)
title: Recommendation update page
participants: @naufalihsank @Ibwedagama @bangunbagustapa
=> Recommendation update page

src/components/Base/JDSRadio/index.vue
title: JDS Radio Button Component
participants: @naufalihsank @maulanayuseph @Ibwedagama @bangunbagustapa @doohanas
=> Create JDS Radio Button Component

src/lang/id.js, src/router/modules/vaccine/pharmacy.js, src/views/immunization/detail/RealizationTableSection.vue, src/views/immunization/update/RealizationSection.vue, src/views/immunization/update/RecommendationSection.vue, src/views/immunization/update/RequestSection.vue, src/views/immunization/update/index.vue
1. create realization section in update page
2. create conditional disable request and recommendation section
1. [[Realisasi Salur] Sebagai PIC Farmasi dapat melakukan Update Realisasi Vaksin](https://app.clickup.com/t/2fzcpnf)
2. [[Realisasi Salur] Sebagai PIC Farmasi dapat melakukan Update Realisasi Penunjang Vaksin](https://app.clickup.com/t/2fzcpmz)
title: Realization Update Page
participants: @naufalihsank @maulanayuseph @adzharamrullah @Ibwedagama @bangunbagustapa @yoslie
=> Create Realization Update Page

src/components/Base/SearchInput/index.vue, src/lang/id.js, src/views/immunization/update/StockSection.vue, src/views/immunization/update/index.vue
1. add `placeholder` prop in `SearchInput` component
2. create stock section in update page
[[Rekomendasi Salur] Sebagai PIC Imunisasi dapat melihat stok vaksin yang tersedia](https://app.clickup.com/t/2fzcc8p)
title: Check stock vaccine
participants: @naufalihsank @maulanayuseph @bangunbagustapa
=> Check stock vaccine

src/components/JDSPagination/index.vue, src/views/immunization/update/StockSection.vue
1. Create `JDSPagination` component
2. Implement `JDSPagination` in stock check section
title: JDS Pagination
participants: @naufalihsank @maulanayuseph @bangunbagustapa @yoslie
=> JDS Pagination

src/lang/id.js, src/router/modules/vaccine/logisticPost.js, src/views/immunization/detail/ActionButton.vue, src/views/immunization/detail/DeliveryPlanTableSection.vue, src/views/immunization/detail/RealizationTableSection.vue, src/views/immunization/detail/index.vue, src/views/logisticPost/deliveryPlan/index.vue
[[Rencana Pengiriman] Sebagai PIC Poslog dapat melihat detail rencana pengiriman](https://app.clickup.com/t/2g51x4c)
title: Delivery detail page
participants: @naufalihsank @maulanayuseph @yoslie
=> Create delivery detail page

src/components/ApplicationForm/FirstStep.vue, src/views/landingPageVaccine/RequirementPopUp.vue
title: Add download link for public vaccine request template
participants: @naufalihsank @maulanayuseph @doohanas
=> Add download link for public vaccine request template

src/components/Base/JDSDatePicker/index.vue, src/views/immunization/detail/ActionButton.vue, src/views/immunization/detail/Dialog.vue, src/views/immunization/detail/RealizationTableSection.vue, src/views/immunization/detail/index.vue
[[Realisasi Salur] Sebagai PIC Farmasi dapat melakukan persetujuan Realisasi Salur](https://app.clickup.com/t/2fzcq4n)
title: Realization submit api
participants: @naufalihsank @Ibwedagama @bangunbagustapa @yoslie
=> Realization submit api

src/store/modules/vaccine/actions.js, src/views/immunization/detail/Dialog.vue, src/views/immunization/detail/index.vue
set name and role dynamic in dialog display
title: Dynamic instance lead in dialog
participants: @naufalihsank @Ibwedagama @bangunbagustapa
=> Dynamic instance lead in dialog

src/components/ApplicationForm/SecondStep.vue, src/components/ApplicationForm/ThirdStepItem.vue, src/lang/id.js, src/router/modules/vaccine/immunization.js, src/router/modules/vaccine/pharmacy.js, src/views/immunization/add/FormSection.vue, src/views/immunization/add/index.vue, src/views/immunization/detail/RealizationTableSection.vue, src/views/immunization/detail/RecommendationTableSection.vue
create add more vaccine page in `realization` and `recommendation` detail pages
[[Rekomendasi Salur] Sebagai PIC Imunisasi dapat melakukan Tambah Rekomendasi Penunjang Vaksin](https://app.clickup.com/t/2fzcc1j)
title: Add more vaccine page
participants: @naufalihsank @maulanayuseph @adzharamrullah @Ibwedagama @bangunbagustapa
=> Add more vaccine page

src/components/Base/JDSDatePicker/index.vue, src/components/Base/JDSFileInput/index.vue, src/components/Base/JDSRadio/index.vue, src/components/Base/JDSSelect/index.vue, src/components/Base/JDSTextField/index.vue, src/utils/vee-validate.js, src/views/immunization/add/FormSection.vue, src/views/immunization/add/index.vue
title: Validate add more vaccine form
participants: @naufalihsank @Ibwedagama @bangunbagustapa @doohanas
=> Validate add more vaccine form

src/store/modules/vaccine/actions.js, src/views/immunization/add/FormSection.vue, src/views/immunization/add/index.vue, src/views/immunization/detail/RealizationTableSection.vue, src/views/immunization/detail/RecommendationTableSection.vue, src/views/immunization/update/RealizationSection.vue, src/views/immunization/update/RecommendationSection.vue, src/views/immunization/update/RequestSection.vue, src/views/immunization/update/index.vue
1. Validate update form
2. Submit update form
3. Submit add form
title: Submit update and add form vaccine
participants: @naufalihsank @yoslie
=> Submit update and add form vaccine

src/views/immunization/add/FormSection.vue, src/views/immunization/detail/ActionButton.vue, src/views/immunization/detail/DeliveryPlanTableSection.vue, src/views/immunization/detail/Dialog.vue, src/views/immunization/detail/RealizationTableSection.vue, src/views/immunization/detail/index.vue, src/views/logisticPost/deliveryPlan/index.vue
title: Submit delivery plan
participants: @naufalihsank @maulanayuseph @Ibwedagama @doohanas
=> Submit delivery plan

src/components/Base/JDSRadio/index.vue, src/views/immunization/detail/RealizationTableSection.vue, src/views/immunization/update/RealizationSection.vue, src/views/immunization/update/index.vue
title: Fix submit form bug
participants: @naufalihsank @maulanayuseph
=> Fix submit form bug

src/views/immunization/update/RealizationSection.vue
title: Change total model name
participants: @naufalihsank @maulanayuseph @Ibwedagama @yoslie
=> Change total model name

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/VaccineSuccess.vue, src/views/immunization/update/StockSection.vue, src/views/landingPageVaccine/index.vue, src/views/permohonan/formPemohon.vue
1. [fix (landing-page): change home redirection route](https://github.com/jabardigitalservice/pikobar-logistik-frontend/commit/518810608e7013a49e1178d977a61d4cace9917c)
2. [fix (fourth-step): change hotline number](https://github.com/jabardigitalservice/pikobar-logistik-frontend/commit/9d015e618b5b238603fda0d264e38e6bdd24215a)
3. [fix (confirmation-step): change home redirection route](https://github.com/jabardigitalservice/pikobar-logistik-frontend/commit/4d22e8bf137d11d0523edf69d5d0d189fd7bb8fc)
4. [feat (landing-page-vaccine): redirect info button to whatsapp hotline](https://github.com/jabardigitalservice/pikobar-logistik-frontend/commit/fce8fbb2fb8c0d58a82d592edffde81689f29891)
5. [fix (landing-page-vaccine): hide tracking feature …
=> Bug Fixing Landing Page

src/components/Base/JDSFileInput/index.vue, src/views/immunization/detail/DeliveryPlanTableSection.vue, src/views/immunization/detail/RealizationTableSection.vue, src/views/immunization/update/index.vue
1. [feat (jds-file-input): disable click on div](https://github.com/jabardigitalservice/pikobar-logistik-frontend/commit/71e246b8ebd2838516ff585d8c4bd078ebf24f2f)
2. [fix (delivery-plan): change status value](https://github.com/jabardigitalservice/pikobar-logistik-frontend/commit/98ddf438375d9c531d04adf7eba6c0bee6a66d4d)
3. [fix (realization-table-section): hide add more button](https://github.com/jabardigitalservice/pikobar-logistik-frontend/commit/63656de4e803ac72739bf87f9102ab4588825f77)
4. [fix (update-form): set product_status in requestData](https://github.com/jabardigitalservice/pikobar-logistik-frontend/commit/ba6f495b2f6fef5cfe403a001a31c3a662b1e65d)
title: Vaccine admin bug fixing
participants: @naufalihsank @maulanayuseph @Ibwedagama @bangunbagustapa
=> Vaccine admin bug fixing

src/views/immunization/detail/ActionButton.vue, src/views/immunization/detail/Dialog.vue, src/views/immunization/update/RequestSection.vue, src/views/immunization/update/StockSection.vue
1. add unit label in update page
2. change delivery plan button and dialog redaction
title: Fix wording in delivery plan module
participants: @naufalihsank
=> hotfix change redaction

src/components/ApplicationForm/FirstStep.vue, src/views/immunization/detail/IdentitySection.vue, src/views/immunization/update/StockSection.vue
1. re render text field in first step public form when instance drop down value changed
2. re render identity in detail vaccine page
3. dynamic updated time value in check stock component
title: Improvement and bug fixing
participants: @naufalihsank @maulanayuseph @maruf12 @Ibwedagama @bangunbagustapa @yoslie
=> Improvement and bug fixing

src/components/Base/JDSButton/index.vue, src/views/immunization/add/FormSection.vue, src/views/immunization/detail/LetterSection.vue, src/views/immunization/detail/index.vue, src/views/immunization/update/RealizationSection.vue, src/views/immunization/update/RecommendationSection.vue, src/views/immunization/update/index.vue
1. dynamic unit in update and add form text field
2. download applicant letter file
3. fix form validation bug
title: Bug fixing and improvements
participants: @naufalihsank @maulanayuseph @Ibwedagama @bangunbagustapa @doohanas
=> Bug fixing and improvements

src/lang/id.js, src/views/immunization/recommendation/index.vue, src/views/immunization/update/RequestSection.vue
1. hide 2 status options in update form
2. adjust status column value in recommendation page
title: Improvement
participants: @naufalihsank @maulanayuseph @maruf12 @Ibwedagama @bangunbagustapa
=> Improvement

src/components/ApplicationForm/FourthStep.vue, src/components/ApplicationForm/VaccineSuccess.vue, src/components/Base/DisabledField/index.vue, src/lang/id.js, src/layout/index.vue, src/router/index.js, src/views/immunization/detail/IdentitySection.vue, src/views/immunization/recommendation/index.vue, src/views/landingPageVaccine/RequirementPopUp.vue
1. temporarily hide some menus in alkes module
2. temporarily hide footer in landing page vaccine
3. accept array value in `DisabledField` component
4. display notes in vaccine detail page
title: Improvements
participants: @naufalihsank @Ibwedagama @yoslie
=> Improvements

src/components/ApplicationForm/ThirdStep.vue, src/components/ApplicationForm/VaccineSuccess.vue, src/layout/Sidebar/SidebarItem.vue, src/views/immunization/update/RecommendationSection.vue, src/views/permohonan/formPemohon.vue
1. fix conditional statement in sidebar item (sentry error)
2. take 100% width in 3rd stepper content
3. remove note input mandatory in update form
4. hide tracking feature info in vaccine form success page
title: Bug fixing
participants: @naufalihsank @maulanayuseph @maruf12 @yoslie @doohanas
=> Bug fixing

src/components/ApplicationForm/ConfirmationStepAdmin.vue, src/components/ApplicationForm/FourthStep.vue, src/views/permohonan/formPemohon.vue
1. Fix post issue in admin form
2. remove draft letter status in admin form
title: hotfix: post issue in admin request alkes form 
participants: @naufalihsank @maulanayuseph @Ibwedagama @bangunbagustapa @maruf12
=> hotfix: post issue in admin request alkes form 

src/components/ApplicationForm/ConfirmationStepAdmin.vue
title: hotfix: fix data display and styling in confirmation step admin alkes
participants: @naufalihsank @maulanayuseph @maruf12 @Ibwedagama @agunghide @bangunbagustapa @yoslie
=> hotfix: fix data display and styling in confirmation step admin alkes

src/views/landingPageVaccine/RequirementPopUp.vue, src/views/landingPageVaccine/index.vue, src/views/permohonan/formPemohon.vue
1. Re Enable Vaccine Public Form
2. Fix vaccine form header in mobile layout
3. Create auto download template link in landing page vaccine
title: Re Enable Vaccine Public Form
participants: @naufalihsank @maruf12
=> Re Enable Vaccine Public Form

src/views/immunization/detail/DeliveryPlanTableSection.vue, src/views/immunization/detail/RealizationTableSection.vue, src/views/immunization/detail/RecommendationTableSection.vue, src/views/immunization/detail/RequestTableSection.vue
title: Disable pagination in all detail table
participants: @naufalihsank @rindibudiaramdhan
=> Hotfix: Disable pagination in all detail table

src/lang/id.js, src/layout/Sidebar/SidebarItem.vue, src/router/index.js, src/router/modules/vaccine/archive.js, src/router/modules/vaccine/logisticPost.js, src/views/archive/index.vue
initiate archive page
title: Archive Page
participants: @naufalihsank @maulanayuseph @agunghide @bangunbagustapa @yoslie @doohanas
=> Archive Page

src/views/archive/index.vue, src/views/immunization/update/RealizationSection.vue, src/views/immunization/update/RecommendationSection.vue, src/views/immunization/update/RequestSection.vue, src/views/immunization/update/StockSection.vue
1. implement auto fill in all section in update form
2. temporarily hide detail button in archive page
3. reset search input in check stock component
title: Improve auto fill update form
participants: @naufalihsank @maulanayuseph @Ibwedagama @agunghide @bangunbagustapa
=> Improve auto fill update form

src/views/immunization/update/RealizationSection.vue, src/views/immunization/update/RecommendationSection.vue, src/views/pharmacy/realization/index.vue
title: Fix recommendation date
participants: @naufalihsank @maruf12
=> Fix recommendation date

src/views/archive/dropdown.js, src/views/archive/index.vue
title: implement verification status in filter
participants: @naufalihsank @doohanas @yoslie @Ibwedagama
=> implement verification status in filter

src/views/archive/dropdown.js, src/views/archive/index.vue
title: Integration verif status filter with poslog
participants: @naufalihsank @maulanayuseph @maruf12 @yoslie
=> Integration verif status filter with poslog

src/views/archive/dropdown.js, src/views/archive/index.vue
title: add integrated status in archive filter page
participants: @naufalihsank @doohanas @agunghide @maulanayuseph @yoslie
=> add integrated status in archive filter page

src/components/Base/JDSTable/index.vue, src/views/archive/index.vue
1. add sorting listener in `JDSTable` component
2. implement sorting in archive page
title: Archive Page Sorting
participants: @naufalihsank @maruf12 @agunghide @doohanas
=> Archive Page Sorting

src/views/archive/index.vue
title: fix sorting api call
participants: @naufalihsank @maulanayuseph @maruf12 @Ibwedagama @agunghide @doohanas
=> fix sorting api call

src/views/archive/index.vue
title: change status value
participants: @naufalihsank @maulanayuseph @doohanas
=> change status value

src/components/Base/JDSTable/index.vue, src/components/Base/JDSTextField/index.vue, src/components/requestVaccine/Footer.vue, src/components/requestVaccine/Header.vue, src/permission.js, src/router/index.js, src/styles/scss/pages/vaccineTracking.scss, src/views/landingPageVaccine/index.vue, src/views/trackingVaccine/ResultCard.vue, src/views/trackingVaccine/TrackingHeader.vue, src/views/trackingVaccine/index.vue
1. unhide tracking section in landing page vaccine
2. fix empty data display message in `JDSTable`
3. create sub label in `JDSTextField`
4. create vaccine tracking page with dummy data page
title: Vaccine Tracking Page
participants: @naufalihsank @maulanayuseph @doohanas @maruf12 @Ibwedagama @agunghide
=> Vaccine Tracking Page

src/components/requestVaccine/Header.vue, src/permission.js, src/router/index.js, src/store/modules/tracking/actions.js, src/styles/scss/pages/vaccineTracking.scss, src/views/trackingVaccine/detail/ProgressTracker.vue, src/views/trackingVaccine/detail/index.vue, src/views/trackingVaccine/index.vue
1. hit api on vaccine tracking input
2. create vaccine tracking detail page
title: Vaccine Tracking Detail Page
participants: @naufalihsank @maulanayuseph @Ibwedagama @agunghide @doohanas
=> Vaccine Tracking Detail Page

src/components/JDSPagination/index.vue, src/views/trackingVaccine/detail/ProgressTracker.vue, src/views/trackingVaccine/index.vue
title: Vaccine Tracking Pagination
participants: @naufalihsank @agunghide @doohanas @yoslie @Ibwedagama
=> Vaccine Tracking Pagination

src/views/archive/index.vue
title: change status display condition in archive filter
participants: @naufalihsank @maruf12 @Ibwedagama @yoslie
=> change status display condition in archive filter

src/views/immunization/detail/index.vue
title: close dialog when submit error
participants: @naufalihsank @maulanayuseph @maruf12 @Ibwedagama @agunghide
=> close dialog when submit error

src/views/immunization/detail/Dialog.vue
title: change button routing page
participants: @naufalihsank @Ibwedagama @agunghide @doohanas
=> change button routing page

src/views/immunization/detail/Dialog.vue
title: fix form dialog show error logic
participants: @naufalihsank @maulanayuseph @maruf12 @agunghide @yoslie
=> fix form dialog show error logic

src/App.vue, src/store/modules/general/actions.js, src/store/modules/general/index.js, src/store/modules/general/mutations.js, src/utils/request.js
title: change logic of general loading
participants: @naufalihsank @maruf12 @Ibwedagama @agunghide @yoslie @doohanas
=> change logic of general loading

src/components/ApplicationForm/ConfirmationStep.vue
title: fix unit props display
participants: @naufalihsank
=> fix unit props display

src/views/immunization/detail/RealizationTableSection.vue
title: unhide add item on realization section
participants: @naufalihsank @maulanayuseph @agunghide @yoslie @doohanas
=> unhide add item on realization section

src/views/immunization/detail/ActionButton.vue, src/views/immunization/detail/Dialog.vue, src/views/immunization/detail/index.vue
title: returning request to realization stage
participants: @naufalihsank @Ibwedagama @agunghide @yoslie @doohanas
=> returning request to realization stage

src/components/ApplicationForm/ConfirmationStep.vue, src/views/permohonan/formPemohon.vue
title: change vaccine request documentation link
participants: @naufalihsank @Ibwedagama @agunghide @doohanas @yoslie
=> change vaccine request documentation link

src/components/Base/DisabledField/index.vue, src/components/Base/JDSSelect/index.vue, src/components/Base/JDSTextField/index.vue, src/store/modules/vaccine/actions.js, src/store/modules/vaccine/index.js, src/store/modules/vaccine/mutations.js, src/utils/vee-validate.js, src/views/immunization/update/RealizationSection.vue, src/views/immunization/update/RecommendationSection.vue, src/views/immunization/update/StockDialog.vue, src/views/immunization/update/index.vue
1. create stock dialog component
2. display current vaccine item stock on recommendation and realization update stage
3. quantity input validation based on current stock in update form
title: Remaining stock vaccine
participants: @naufalihsank @Ibwedagama @agunghide @doohanas
=> Remaining stock vaccine

src/store/modules/vaccine/actions.js, src/views/immunization/update/RealizationSection.vue, src/views/immunization/update/RecommendationSection.vue
title: fix check vaccine item stock
participants: @naufalihsank @Ibwedagama @agunghide @yoslie @doohanas
=> fix check vaccine item stock

src/views/immunization/update/RealizationSection.vue, src/views/immunization/update/RecommendationSection.vue
title: hotfix check vaccine item stock
participants: @naufalihsank @agunghide @yoslie
=> hotfix: change vaccine_request_id value

src/components/Base/JDSTextField/index.vue, src/helpers/tableDisplay.js, src/lang/id.js, src/store/modules/vaccine/actions.js, src/views/immunization/adminVerification/index.vue, src/views/immunization/detail/IdentitySection.vue, src/views/immunization/detail/index.vue, src/views/immunization/recommendation/index.vue, src/views/immunization/update/RealizationSection.vue, src/views/immunization/update/RecommendationSection.vue, src/views/immunization/update/RequestSection.vue, src/views/immunization/update/StockDialog.vue, src/views/logisticPost/deliveryPlan/index.vue, src/views/pharmacy/realization/index.vue
1. `CITO` button on verification detail stage
2. Hide recommendation section in vaccine stock dialog
3. Formatting number display in vaccine stock dialog
title: Vaccine Request CITO Status
participants: @naufalihsank @Ibwedagama @agunghide @yoslie
=> Vaccine Request CITO Status

src/views/immunization/detail/Dialog.vue
title: implement post rating on back dialog button
participants: @naufalihsank @maulanayuseph @maruf12 @doohanas
=> Implement post rating on back dialog button

src/components/ApplicationForm/ConfirmationStep.vue, src/components/ApplicationForm/VaccineSuccess.vue, src/components/EmoticonRating/index.vue
Changes:
- Add rating in mobile layout
Related:
https://app.clickup.com/t/2t2derw
title: Add rating in mobile layout
participants: @maruf12 @naufalihsank @doohanas @Ibwedagama @yoslie @maulanayuseph
=> Add rating in mobile layout

src/lang/id.js, src/router/modules/pengajuanLogistik.js, src/views/pengajuanLogistik/detailRealization.vue, src/views/pengajuanLogistik/list.vue
Changes:
- Update list alkes
Task:
- https://app.clickup.com/t/2y862h4
title: List archive
participants: @maruf12 @naufalihsank @Ibwedagama @doohanas @maulanayuseph
=> List archive

src/lang/id.js, src/router/modules/pengajuanLogistik.js, src/views/pengajuanLogistik/list.vue
=> Revamp list

src/views/pengajuanLogistik/detailRealization.vue
Changes:
- Fixing detail info
Related:
https://app.clickup.com/3808590/v/b/6-192787935-2
title: Fixing detail info
participants: @maruf12 @naufalihsank @yoslie @maulanayuseph @Ibwedagama @rizfirman
=> Fixing detail info
